#!/bin/bash
set -euo pipefail

if [[ $@ = "-h" ]]; then {
	echo "Runs all given commands in paralell and kills them on exit"
	echo "Usage: $1 [cmd...]"
	exit 0
} fi

declare -a PID_LIST

for cmd in "$@"; do {
	echo "Starting \"$cmd\""
	$SHELL -c "$cmd" & pid=$!
	PID_LIST+=" $pid";
} done

trap "kill $PID_LIST" SIGINT

wait $PID_LIST