#! /bin/bash

PORTS=""
if [ $# > 0 ]; then
	PORTS=$* 
else
	echo "Is your port in use? Then just kill the blocking process!"
	echo "Port number:"
	read PORTS
fi

lsof -i:$PORTS |
tail -n -1 |
fzf |
grep -Po '\d+' | # all numbers..
head -n 1 |  # ..of which the first is the ip
xargs -r kill -9 # kill it (-r means olny run when there is input)
